name: PlanetLobby
version: '${version}'
description: '${description}'
main: kr.planetearth.plugins.planetlobby.PlanetLobby
api-version: '1.20'

commands:
  랭크보상:
    description: 랭크보상
  PermissionGivePerUUID:
    description: PermissionGivePerUUID